Doris-Siu/in-a-class-of-our-own

client/src/pages/Home.css
=> Addes some default CSS rules

client/src/App.js, client/src/pages/App-info/ApplicationInfo.css, client/src/pages/App-info/ApplicationInfo.js, client/src/pages/ApplicationInfo.js
=> Create ApplicationInfo page with responsive design

tables.sql
=> data table structure

package-lock.json, package.json, server/api.js, server/app.js
=> database trainee and cohorts table read and post

server/api.js
=> extracteddata and milestone table read and post

client/src/pages/Dashboard/Components/Overview/Overview.js, client/src/pages/Dashboard/Dashboard.js, client/src/pages/Dashboard/Functions/checkMilestone.js
=> Create checkMilestone function to return 1/2/3

client/src/pages/Dashboard/Components/SetMilestone/SetMilestone.css, client/src/pages/Dashboard/Components/SetMilestone/SetMilestone.js
=> Create page - Dashboard/set milestone

client/src/pages/Dashboard/Components/CyfMilestone/CyfMilestone.js
=> Cyf milestone table added

tables.sql
=> new table added to the database

server/api.js, tables.sql
=> fetch github repos and codewars and post req to extracteddata table

client/src/Components/Banner/Banner.css, client/src/Components/Banner/Banner.js, client/src/Components/Footer/Footer.js, client/src/pages/Dashboard/Components/CyfMilestone/CyfMilestone.js, client/src/pages/Dashboard/Components/DashboardHeader/DashboardHeader.js, client/src/pages/Dashboard/Components/Overview/Overview.css, client/src/pages/Dashboard/Components/Overview/Overview.js, client/src/pages/Dashboard/Components/Sidebar/Sidebar.css, client/src/pages/Dashboard/Components/Sidebar/Sidebar.js, client/src/pages/Register/Register.css
closes #46 
It should make all pages and elements 100% accessible.
=> Improve pages accessibility

client/src/pages/Register/Register.js, package-lock.json, package.json, server/api.js
=> Backend for regitser page

server/api.js
=> github prs functionality added to backend post request

client/src/App.js, client/src/Components/Header/Header.js
=> GitHub login - frontend

client/src/App.js, server/api.js, server/server.js
=> github authentication (server side)

client/src/App.js, client/src/pages/Register/Register.js, server/api.js, server/server.js
=> Set up diff. routes after user login with Github

client/src/App.js, client/src/pages/Register/Register.js, server/api.js, server/server.js
=> Add get endpoint to query specific trainee's data with github username

server/api.js
=> automated extracteddata table inputs

client/src/pages/Register/Register.js
=> Preset the github username in the register form

server/api.js
=> final milestone status returned to clientside

server/api.js, tables.sql
=> updated tables columns in Database

client/src/Components/Header/Header.js, client/src/pages/Dashboard/Components/DashboardHeader/DashboardHeader.js, client/src/pages/Register/Register.js, package-lock.json, package.json, server/api.js, server/utils/config.js
=> Implement logout logic & redirect to homepage

client/src/pages/Dashboard/Components/Overview/Overview.css, client/src/pages/Dashboard/Components/Overview/Overview.js, client/src/pages/Dashboard/Dashboard.css, client/src/pages/Dashboard/Dashboard.js, client/src/pages/Register/Register.js, server/api.js
=> Fixing bug
